#!/bin/bash

# AUTHOR:   (c) Rob W 2012
#           modified by MHC (http://askubuntu.com/users/81372/mhc)
#           and by Rodolfo Carvalho
# EDITED BY: EGGSY
# ADDED: Region selection capability.
# NAME:  GIFRecord 0.1-fedora
# DESCRIPTION:  A script to record GIF screencasts.
# LICENSE:  GNU GPL v3 (http://www.gnu.org/licenses/gpl.html)
# DEPENDENCIES:   byzanz,zenity,notify-send,xrectsel

# Time and date
TIME=$(date +"%Y-%m-%d_%H%M%S")

# Delay before starting
DELAY=5

# Standard screencast folder
OUTPUT_DIR=$(xdg-user-dir PICTURES 2>/dev/null || echo "/tmp")

# Sound notification to let one know when recording is about to start (and ends)
beep() {
    paplay /usr/share/sounds/freedesktop/stereo/message-new-instant.oga &
}

# GUI prompt for user input
prompt() {
    title=$1
    description=$2
    default=$3
    value=$(zenity --entry --title "$title" --text "$description" --entry-text "$default" --width 200 --height 100 2>/dev/null)
    if [[ $? -eq 0 && "$value" != "" ]]; then
        echo $value
    else
        echo $default
    fi
}

# Check if "xrectsel" is available
which xrectsel 1>/dev/null
if [[ $? -ne 0 ]]; then
    echo "xrectsel binary for region selection is not available"
    echo "download it from: https://github.com/lolilolicon/xrectsel"
    exit 1
fi

# Custom recording duration as set by user
DURATION=$(prompt "Recoding duration" "Enter the screencast duration in seconds" "10")

# Custom format set by user
FORMAT=$(prompt "Ouput format" "Enter your output format (gif, mp4)" "gif")

OUTPUT_FILE="$OUTPUT_DIR/screencast_$TIME.$FORMAT"

# Window geometry - uses "xrectsel" for region selection.
XWININFO=$(xrectsel)
W=$(echo $XWININFO | cut -d'x' -f 1)
H=$(echo $XWININFO | cut -d'x' -f 2 | cut -d'+' -f 1)
X=$(echo $XWININFO | cut -d'x' -f 2 | cut -d'+' -f 2 | cut -d'+' -f 1)
Y=$(echo $XWININFO | rev | cut -d'+' -f 1 | rev)

# Notify the user of recording time and delay
echo "Recording duration set to $DURATION seconds. Recording will start in $DELAY seconds."

# Actual recording
sleep $DELAY
beep
byzanz-record -c --verbose --delay=0 --duration=$DURATION --x=$X --y=$Y --width=$W --height=$H "$OUTPUT_FILE"
beep
echo "Screencast saved to $OUTPUT_FILE"
